services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    image: email-microservice
    ports:
      - '3000:5000'
    restart: unless-stopped
    container_name: email-microservice
