services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:5000'
    networks:
      - app-network
    restart: unless-stopped
    container_name: email-microservice
networks:
  app-network:
    driver: bridge
