services:
  microservice:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:5000'
    networks:
      - app-network
    restart: unless-stopped
    env_file:
      - .env # Carga las variables desde el archivo .env

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./public:/usr/share/nginx/html
    ports:
      - '8085:80'
    depends_on:
      - microservice
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
